apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: lambda-attach
spec:
  forProvider:
    policyArnRef:
      name: lambdapolicy
    roleNameRef:
      name: lambdarole
