apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: lambda-sg
spec:
  forProvider:
    description: lambda-sg
    egress: 
    - fromPort: 5432
      ipProtocol: tcp
      toPort: 5432
      ipRanges:
        - cidrIp: 10.0.0.0/16
    groupName: prod-lambda-sg
    region: us-east-1
    vpcIdRef:
      name: vpc-us-east-1
