apiVersion: lambda.aws.crossplane.io/v1beta1
kind: Function
metadata:
  name: function
spec:
  forProvider:
    code:
      # s3Bucket: prod-lambda-code-bucket0987654321
      s3Bucket: lambda-to-rds
      s3Key: lambda-to-rds.zip
    handler: lambda-to-rds.hanlder
    runtime: python3.10
    region: us-east-1
    roleRef:
      name: lambdarole
    vpcConfig:
      securityGroupIDRefs:
      - name: lambda-sg
      subnetIDRefs:
      - name: subnet-us-east-1a
      - name: subnet-us-east-1b
      - name: subnet-us-east-1c