apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  labels:
    testing.upbound.io/example-name: ecs-allow-policy
  name: ecs-allow-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "rds:*",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*"
          }
        ]
      }