apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBListener
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-listener
  name: sample-app-listener
spec:
  forProvider:
    defaultAction:
    - forward:
      - targetGroup:
        # - arn: << FILL_THIS_IN >>
        - arnSelector:
            matchLabels:
              testing.upbound.io/example-name: sample-app-target-group
      type: forward
    loadBalancerArnSelector:
      matchLabels:
        testing.upbound.io/example-name: sample-app-alb
    port: 80
    protocol: HTTP # default
    region: us-east-1