apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  labels:
    testing.upbound.io/example-name: rds-subnet-group
  name: rds-subnet-group
spec:
  forProvider:
    description: rds-subnet-group
    region: us-east-1
    subnetIdRefs:
    - name: subnet-us-east-1a
    - name: subnet-us-east-1b
    - name: subnet-us-east-1c