apiVersion: acm.aws.upbound.io/v1beta1
kind: Certificate
metadata:
  labels:
    testing.upbound.io/example-name: certificate
  name: certificate
spec:
  forProvider:
    domainName: example-dns.mftesting.io
    region: us-east-1
    validationMethod: DNS