apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-target-group
  name: sample-app-target-group
spec:
  forProvider:
    healthCheck:
      enabled: false
    name: sample-app-target-group
    port: 8081 # container port
    protocol: HTTP
    region: us-east-1
    targetType: ip # for Fargate
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1