apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBListener
metadata:
  labels:
    testing.upbound.io/example-name: http-listener
  name: http-listener
spec:
  forProvider:
    # NEEDS TO POINT TO TARGET GROUP
    # defaultAction:
    # - type: fixed-response
    #   fixedResponse:
    #     - contentType: text/plain
    #       messageBody: http-listener rule reached
    #       statusCode: "200"
    loadBalancerArnSelector:
      matchLabels:
        testing.upbound.io/example-name: application-lb
    port: 80
    region: us-east-1