apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  labels:
    testing.upbound.io/example-name: http-target-group
  name: http-target-group
spec:
  forProvider:
    name: http-target-group
    port: 8081 # container port
    protocol: HTTP
    region: us-east-1
    targetType: ip # for Fargate
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1