# ALB
apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LB
metadata:
  labels:
    testing.upbound.io/example-name: application-lb
  name: application-lb
spec:
  forProvider:
    enableDeletionProtection: false #default
    internal: true
    loadBalancerType: application #default
    name: application-lb
    region: us-east-1
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: sg-us-east-1
    subnetMapping:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet-us-east-1a
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet-us-east-1b