apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskDefinition
metadata:
  labels:
    testing.upbound.io/example-name: sample-app-task
  name: sample-app-task
spec:
  forProvider:
    executionRoleArn: arn:aws:iam::011882408883:role/ecsTaskExecutionRole
    containerDefinitions: |
      [
        {
          "name": "sample-app-container",
          "image": "011882408883.dkr.ecr.us-east-1.amazonaws.com/sample-app:latest",
          "cpu": 0,
          "memoryReservation": 2048,
          "essential": true,
          "PortMappings": [
            {
            "hostPort": 8081,
            "ContainerPort" : 8081,
            "Protocol" : "tcp" 
            }
          ]
        }
      ]
    cpu: '1024' # must be string
    family: sample-app-task
    memory: '2048' # must be string
    networkMode: awsvpc
    region: us-east-1
    requiresCompatibilities: 
      - FARGATE
    # WHY IS THIS AN ARN ONLY? NO Ref or matchLabels Selector?
    taskRoleArn: arn:aws:iam::011882408883:role/ecs-to-rds

# "PortMappings": [
  # {
  #   "AppProtocol" : String,
  #   "ContainerPort" : Integer,
  #   "ContainerPortRange" : String,
  #   "HostPort" : Integer,
  #   "Name" : String,
  #   "Protocol" : String
  # }
# ]