apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This resource requires manual intervention
      for adding task definition revision. Otherwise, resource will be updated
      to use latest revision.
  labels:
    testing.upbound.io/example-name: sample-app-service
  name: sample-app-service
spec:
  forProvider:
    # according to Upbound docs, cluster should be the ARN, but throws "InvalidParameterException: Unsupported resource type: cluster:"
    # works when given the name of the cluster, not ARN
    cluster: sample-app-cluster 
    #
    # The other two cluster field options also don't work because it resolves to ARN, API request just wants cluster name
    #
    # clusterSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: sample-app-cluster
    #
    # clusterRef:
    #   name: sample-app-cluster
    #
    desiredCount: 1
    launchType: FARGATE
    loadBalancer:
      - containerName: sample-app-container	
        containerPort: 8081
        #
        # no Selector or Ref option for targetGroupArn?? must be hardcoded??
        # targetGroupArn: << FILL_THIS_IN >>
        targetGroupArn: arn:aws:elasticloadbalancing:us-east-1:011882408883:targetgroup/sample-app-target-group/70c077ff70d257a2
    # networkConfiguration required for FARGATE (networkMode: awsvpc)
    networkConfiguration: 
      - assignPublicIp: true
        securityGroupSelector:
          matchLabels:
            testing.upbound.io/example-name: sg-us-east-1
        subnetSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet-us-east-1a
            testing.upbound.io/example-name: subnet-us-east-1b
    propagateTags: TASK_DEFINITION
    region: us-east-1
    taskDefinition: sample-app-task