apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    testing.upbound.io/example-name: rta-us-east-1a
  name: rta-us-east-1a
spec:
  forProvider:
    region: us-east-1
    # gatewayIdSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: internet-gateway-us-east-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: routetable-us-east-1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet-us-east-1a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  labels:
    testing.upbound.io/example-name: rta-us-east-1b
  name: rta-us-east-1b
spec:
  forProvider:
    region: us-east-1
    # gatewayIdSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: internet-gateway-us-east-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: routetable-us-east-1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet-us-east-1b
