apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  labels:
    testing.upbound.io/example-name: routetable-us-east-1
  name: routetable-us-east-1
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1