apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: prod-lambdapolicy
spec:
  forProvider:
    name: prod-lambdapolicy
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "logs:CreateLogGroup",
                      "logs:CreateLogStream",
                      "logs:PutLogEvents",
                      "ec2:CreateNetworkInterface",
                      "ec2:DescribeNetworkInterfaces",
                      "ec2:DeleteNetworkInterface",
                      "ec2:AssignPrivateIpAddresses",
                      "ec2:UnassignPrivateIpAddresses"
                  ],
                  "Resource": "*"
              }
          ]
      }
  # providerConfigRef:
  #   name: prod