apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: prod-lambda-attach
spec:
  forProvider:
    policyArnRef:
      name: prod-lambdapolicy
    roleNameRef:
      name: prod-lambdarole
  # providerConfigRef:
  #   name: prod