apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  labels:
    testing.upbound.io/example-name: ec2-role-policy-attachment
  name: ec2-role-policy-attachment
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: ec2-allow-policy 
    roleSelector:
      matchLabels: 
        testing.upbound.io/example-name: ec2-to-rds