apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: This resource has a password secret reference.
  labels:
    testing.upbound.io/example-name: rds-sample-app-instance
  name: rds-sample-app-instance
spec:
  forProvider:
    dbSubnetGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rds-subnet-group
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    engine: postgres
    engineVersion: "13.7"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    name: SampleAppDB # DBName must begin with a letter and contain only alphanumeric characters
    passwordSecretRef:
      key: password
      name: rds-instance-secret
      namespace: upbound-system
    publiclyAccessible: false
    region: us-east-1
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    username: adminuser
    vpcSecurityGroupIdRefs:
    - name: sg-us-east-1
    # Just creates another secret api resource
  # writeConnectionSecretToRef:
  #   name: rds-sample-app-secret-out
  #   namespace: upbound-system