apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  labels:
    testing.upbound.io/example-name: ecs-to-rds
  name: ecs-to-rds
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
