apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  labels:
    testing.upbound.io/example-name: ecs-allow-policy
  name: ecs-allow-policy
spec:
  forProvider:
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "rds:*",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Action": "ecs:*",
            "Effect": "Allow",
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
          }
        ]
      }
    name: ecs-allow-policy
