apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata: 
  name: default
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: upbound-system
    source: Secret
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata: 
  name: default
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: upbound-system
    source: Secret