apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    testing.upbound.io/example-name: sg-us-east-1
  name: sg-us-east-1
spec:
  forProvider:
    description: dev-security-group                # REQUIRED
    groupName: dev-security-group                  # REQUIRED
    ingress:
      - fromPort: 5432
        ipProtocol: tcp
        toPort: 5432
        ipRanges:
          - cidrIp: 10.0.0.0/16
      #   userIdGroupPairs:
      #   - groupId: sg-0add1a6fd4ee893be
      #     userId: "126251989794"
          # vpcId: vpc-0d88068f52bb517ef
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1