apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  labels:
    testing.upbound.io/example-name: routetable-us-east-1
  name: routetable-us-east-1
spec:
  forProvider:
    associations:
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: subnet-us-east-1a
    - subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: subnet-us-east-1b
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-us-east-1