apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    testing.upbound.io/example-name: vpc-us-east-1
  name: vpc-us-east-1
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-east-1