# Doesn't work, error from crossplane is:
# observe failed: cannot run refresh: refresh failed: 
# InvalidParameterException: Task Definition can not be blank.:

apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskDefinition
metadata:
  annotations:
    crossplane.io/external-name: arn:aws:ecs:us-east-1:011882408883:task-definition/sample-app-task-def:1
  labels:
    testing.upbound.io/example-name: sample-task
  name: sample-task
spec:
  forProvider:
    family: sample-task-family
    region: us-east-1
    requiresCompatibilities: 
      - FARGATE
    networkMode: awsvpc
    memory: '2048' # must be string
    cpu: '1024' # must be string
    executionRoleArn: arn:aws:iam::011882408883:role/ecsTaskExecutionRole
    containerDefinitions: |
      [
        {
          "dnsSearchDomains": null,
          "environmentFiles": null,
          "logConfiguration": {
            "logDriver": "awslogs",
            "secretOptions": null,
            "options": {
              "awslogs-group": "/ecs/sample-app-task-def",
              "awslogs-region": "us-east-1",
              "awslogs-stream-prefix": "ecs"
            }
          },
          "entryPoint": [],
          "portMappings": [
            {
              "hostPort": 8081,
              "protocol": "tcp",
              "containerPort": 8081
            }
          ],
          "command": [],
          "linuxParameters": null,
          "cpu": 0,
          "environment": [],
          "resourceRequirements": null,
          "ulimits": null,
          "dnsServers": null,
          "mountPoints": [],
          "workingDirectory": null,
          "secrets": null,
          "dockerSecurityOptions": null,
          "memory": null,
          "memoryReservation": 2048,
          "volumesFrom": [],
          "stopTimeout": null,
          "image": "011882408883.dkr.ecr.us-east-1.amazonaws.com/sample-app:latest",
          "startTimeout": null,
          "firelensConfiguration": null,
          "dependsOn": null,
          "disableNetworking": null,
          "interactive": null,
          "healthCheck": null,
          "essential": true,
          "links": null,
          "hostname": null,
          "extraHosts": null,
          "pseudoTerminal": null,
          "user": null,
          "readonlyRootFilesystem": null,
          "dockerLabels": null,
          "systemControls": null,
          "privileged": null,
          "name": "sample-app-container"
        }
      ]
