apiVersion: acmpca.aws.upbound.io/v1beta1
kind: CertificateAuthority
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: Creation of this resource costs over $100,
      so it is not suitable for continuous testing.
  name: example
spec:
  forProvider:
    certificateAuthorityConfiguration:
      - keyAlgorithm: RSA_4096
        signingAlgorithm: SHA512WITHRSA
        subject:
          - commonName: example.com
    permanentDeletionTimeInDays: 7
    region: us-east-1
    type: ROOT